---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  playbook: nginx.yml
  #ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all

platforms:
  - name: centos

suites:
  - name: default
    run_list:
    attributes:
