---
- hosts: lep
  sudo: true
  tasks:
    - include: epel.yml
    - include: yum_upgrade.yml
    - name: Installs nginx web server
      yum: pkg=nginx state=installed
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started enabled=yes
